-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '2bc2201cf66bb766' HASH '2b59abe1d41d26706c0a8035b1c6b7dd80816fd2a1c513d85289932ea4ed07a5' ADMIN;         
CREATE SEQUENCE "PUBLIC"."COPIES_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;          
CREATE CACHED TABLE "PUBLIC"."flyway_schema_history"(
    "installed_rank" INTEGER NOT NULL,
    "version" CHARACTER VARYING(50),
    "description" CHARACTER VARYING(200) NOT NULL,
    "type" CHARACTER VARYING(20) NOT NULL,
    "script" CHARACTER VARYING(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" CHARACTER VARYING(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
);               
ALTER TABLE "PUBLIC"."flyway_schema_history" ADD CONSTRAINT "PUBLIC"."flyway_schema_history_pk" PRIMARY KEY("installed_rank");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.flyway_schema_history;   
INSERT INTO "PUBLIC"."flyway_schema_history"("installed_rank", "version", "description", "type", "script", "checksum", "installed_by", "installed_on", "execution_time", "success") VALUES
(-1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, 'SA', TIMESTAMP '2026-06-16 13:03:13.740068', 0, TRUE),
(1, '1', 'creacion tabla items', 'SQL', 'V1__creacion_tabla_items.sql', 1802358572, 'SA', TIMESTAMP '2026-06-16 13:06:23.855542', 16, FALSE); 
CREATE INDEX "PUBLIC"."flyway_schema_history_s_idx" ON "PUBLIC"."flyway_schema_history"("success" NULLS FIRST);               
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_COPIES"(
    "ACQUIRED_AT" DATE,
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "ITEM_ID" BIGINT,
    "RESERVED_BY" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."HTE_COPIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("RN_");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_COPIES;              
CREATE CACHED TABLE "PUBLIC"."COPIES"(
    "ACQUIRED_AT" DATE,
    "ID" BIGINT NOT NULL,
    "ITEM_ID" BIGINT NOT NULL,
    "RESERVED_BY" CHARACTER VARYING(255)
);      
ALTER TABLE "PUBLIC"."COPIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_76" PRIMARY KEY("ID");      
-- 15 +/- SELECT COUNT(*) FROM PUBLIC.COPIES; 
INSERT INTO "PUBLIC"."COPIES"("ACQUIRED_AT", "ID", "ITEM_ID", "RESERVED_BY") VALUES
(DATE '2026-06-16', 1, 1, ''),
(DATE '2026-06-16', 2, 2, ''),
(DATE '2026-06-16', 3, 3, ''),
(DATE '2026-06-16', 4, 4, ''),
(DATE '2026-06-16', 5, 5, ''),
(DATE '2026-06-16', 6, 6, ''),
(DATE '2026-06-16', 7, 7, ''),
(DATE '2026-06-16', 8, 8, ''),
(DATE '2026-06-16', 9, 9, ''),
(DATE '2026-06-16', 10, 10, ''),
(DATE '2026-06-16', 11, 11, ''),
(DATE '2026-06-16', 12, 12, ''),
(DATE '2026-06-16', 13, 13, ''),
(DATE '2026-06-16', 14, 14, ''),
(DATE '2026-06-16', 15, 15, '');               
CREATE CACHED TABLE "PUBLIC"."ITEMS"(
    "DURATION" INTEGER NOT NULL,
    "MINIMUM_AGE" INTEGER,
    "RELEASED_AT" DATE,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 16) NOT NULL,
    "AUTHOR" CHARACTER VARYING(255),
    "IMAGE" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "TYPE" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 15 +/- SELECT COUNT(*) FROM PUBLIC.ITEMS;  
INSERT INTO "PUBLIC"."ITEMS"("DURATION", "MINIMUM_AGE", "RELEASED_AT", "ID", "AUTHOR", "IMAGE", "TITLE", "TYPE") VALUES
(1196, 13, DATE '2010-08-31', 1, 'Brandon Sanderson', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1433753824i/25686515.jpg', 'El Camino de Los Reyes', 'libro'),
(391, 12, DATE '1980-05-01', 2, 'John Kennedy Toole', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1428933691i/3168524.jpg', 'La Conjura de los Necios', 'libro'),
(335, 12, DATE '1997-01-01', 3, 'Rand Miller', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1231009753i/6063829.jpg', 'El Libro de Atrus', 'libro'),
(872, 16, DATE '2009-05-30', 4, 'Patrick Rothfuss', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1419003669i/6483211.jpg', 'El Nombre del Viento', 'libro'),
(658, 13, DATE '1965-06-01', 5, 'Frank Herbert', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg', 'Dune', 'libro'),
(120, 14, DATE '2015-01-01', 6, U&'Vlaada Chv\00e1til', 'https://cf.geekdo-images.com/fVwPntkJKgaEo0rIC0RwpA__itemrep/img/TF5TpehpgE7XvNSRzSSWjnYCbLc=/fit-in/246x300/filters:strip_icc()/pic2663291.jpg', 'Through the Ages', 'juego'),
(100, 12, DATE '2016-01-01', 7, 'Alexander Pfister', 'https://cf.geekdo-images.com/u1l0gH7sb_vnvDvoO_QHqA__itemrep/img/s3qAGoXVCK6gA8nsHDICfZ4Jc1c=/fit-in/246x300/filters:strip_icc()/pic4887376.jpg', 'Great Western Trail', 'juego'),
(80, 10, DATE '2018-01-01', 8, 'Cole Wehrle', 'https://cf.geekdo-images.com/JUAUWaVUzeBgzirhZNmHHw__itemrep/img/sQgkl-_hydBVvQHAMLt2Zk_3dwI=/fit-in/246x300/filters:strip_icc()/pic4254509.jpg', 'Root', 'juego'),
(90, 12, DATE '2007-01-01', 9, 'Uwe Rosenberg', 'https://cf.geekdo-images.com/dDDo2Hexl80ucK1IlqTk-g__itemrep/img/DzC9cA0TNmWUO7WLdl4-uFHfO_k=/fit-in/246x300/filters:strip_icc()/pic831744.jpg', 'Agricola', 'juego'),
(45, 8, DATE '2017-01-01', 10, 'Michael Kiesling', 'https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__itemrep/img/6oRLPDvy4zz3gOZM6e6NzIk8Seg=/fit-in/246x300/filters:strip_icc()/pic6973671.png', 'Azul', 'juego'),
(49, 16, DATE '1996-10-15', 11, 'Korn', 'https://lastfm.freetls.fastly.net/i/u/500x500/41006b2356b2420e9fe2747540310d50.jpg', 'Life Is Peachy', 'disco'),
(54, 16, DATE '1999-11-01', 12, 'Korn', 'https://lastfm.freetls.fastly.net/i/u/500x500/983f577430dbf57f96169ccda8d24115.jpg', 'Issues', 'disco'),
(38, 16, DATE '2017-03-09', 13, 'Los Punsetes', 'https://lastfm.freetls.fastly.net/i/u/500x500/d0e1b70a129d1709294aa23a94850bcf.jpg', U&'\00a1Viva!', 'disco'),
(55, 16, DATE '2001-08-28', 14, 'Slipknot', 'https://lastfm.freetls.fastly.net/i/u/770x0/c3161dcc6d26898bfd1574eb65cef7d5.jpg#c3161dcc6d26898bfd1574eb65cef7d5', 'Iowa', 'disco'),
(66, 16, DATE '2003-04-07', 15, 'Opeth', 'https://www.last.fm/es/music/Opeth/Damnation/+images/c974cc0caf0beec33bdb9f9392683d30', 'Damnation', 'disco');       
CREATE CACHED TABLE "PUBLIC"."LOANS"(
    "COPY_ID" BIGINT NOT NULL,
    "EXPIRED_AT" TIMESTAMP(6),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "RETURNED_AT" TIMESTAMP(6),
    "STARTED_AT" TIMESTAMP(6)
);         
ALTER TABLE "PUBLIC"."LOANS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_45" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LOANS;   
CREATE CACHED TABLE "PUBLIC"."MEMBERS"(
    "BIRTH_DATE" DATE,
    "PREMIUM" BOOLEAN NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 11) NOT NULL,
    "CUENTA" CHARACTER VARYING(255),
    "EMAIL" CHARACTER VARYING(255),
    "PERFIL" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."MEMBERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");      
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.MEMBERS;
INSERT INTO "PUBLIC"."MEMBERS"("BIRTH_DATE", "PREMIUM", "ID", "CUENTA", "EMAIL", "PERFIL", "USERNAME") VALUES
(DATE '2009-05-14', FALSE, 1, NULL, 'maria.garcia@fakemail.com', 'estudiante', 'maria.garcia'),
(DATE '2008-11-02', FALSE, 2, NULL, 'carlos.martinez@fakemail.com', 'estudiante', 'carlos.martinez'),
(DATE '2007-03-28', FALSE, 3, NULL, 'laura.lopez@fakemail.com', 'estudiante', 'laura.lopez'),
(DATE '1999-07-19', FALSE, 4, NULL, 'javier.sanchez@fakemail.com', 'profesor', 'javier.sanchez'),
(DATE '1995-01-10', FALSE, 5, NULL, 'ana.fernandez@fakemail.com', 'profesor', 'ana.fernandez'),
(DATE '1988-09-05', FALSE, 6, NULL, 'david.gonzalez@fakemail.com', 'profesor', 'david.gonzalez'),
(DATE '1982-12-22', FALSE, 7, NULL, 'sofia.rodriguez@fakemail.com', 'profesor', 'sofia.rodriguez'),
(DATE '1978-04-03', FALSE, 8, NULL, 'pablo.perez@fakemail.com', 'profesor', 'pablo.perez'),
(DATE '2011-06-30', FALSE, 9, NULL, 'isabel.diaz@fakemail.com', 'visitante', 'isabel.diaz'),
(DATE '2006-10-08', FALSE, 10, NULL, 'juan.martin@fakemail.com', 'estudiante', 'juan.martin');   
ALTER TABLE "PUBLIC"."LOANS" ADD CONSTRAINT "PUBLIC"."FKLINSEUU52XB6WKNRXP9AE0UWU" FOREIGN KEY("COPY_ID") REFERENCES "PUBLIC"."COPIES"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."LOANS" ADD CONSTRAINT "PUBLIC"."FKCX90N1MINPB22V3JW4OJINQM" FOREIGN KEY("MEMBER_ID") REFERENCES "PUBLIC"."MEMBERS"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."COPIES" ADD CONSTRAINT "PUBLIC"."FKAQ8V2O6LM5D7CMQR05KUHC9P0" FOREIGN KEY("ITEM_ID") REFERENCES "PUBLIC"."ITEMS"("ID") NOCHECK;         
