openapi: 3.0.0
info:
  title: Biblioteca API
  version: "1.0.0"
paths:
  /libros:
    get:
      summary: Obtener lista de libros
      responses:
        '200':
          description: Lista de libros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookSummary'
components:
  schemas:
    BookSummary:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
    BookDetail:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
        type:
          type: string
        entrada:
          type: integer